# Generated by Django 4.2.3 on 2023-07-20 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id_pendidikan', models.AutoField(primary_key=True, serialize=False)),
                ('tingkat_pendidikan', models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas'), ('D1', 'Diploma Satu'), ('D2', 'Diploma Dua'), ('D3', 'Diploma Tiga'), ('D4', 'Diploma Empat'), ('S1', 'Sarjana Satu'), ('S2', 'Sarjana Dua'), ('S3', 'Sarjana Tiga')], default='SD', max_length=3)),
                ('lembaga_pendidikan', models.CharField(max_length=200)),
                ('fakultas_pendidikan', models.CharField(blank=True, max_length=200)),
                ('jurusan_pendidikan', models.CharField(blank=True, max_length=200)),
                ('gelar_depan_pendidikan', models.CharField(blank=True, max_length=100)),
                ('gelar_belakang_pendidikan', models.CharField(blank=True, max_length=100)),
                ('nomor_seri_ijazah_pendidikan', models.CharField(max_length=200)),
                ('tanggal_terbit_ijazah_pendidikan', models.DateField()),
                ('file_ijazah_pendidikan', models.FileField(upload_to='media/pendidikan/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.AutoField(primary_key=True, serialize=False)),
                ('nip_pegawai', models.IntegerField(default=0, unique=True)),
                ('nama_pegawai', models.CharField(max_length=200)),
                ('tempat_lahir_pegawai', models.CharField(max_length=200)),
                ('tanggal_lahir_pegawai', models.DateField()),
                ('jenis_kelamin_pegawai', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200)),
                ('surel_pegawai', models.EmailField(max_length=200)),
                ('telepon_pegawai', models.CharField(max_length=200)),
                ('aktif_pegawai', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pangkat',
            fields=[
                ('id_pangkat', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pangkat', models.CharField(choices=[('IA', 'Juru Muda'), ('IB', 'Juru Muda Tingkat 1'), ('IC', 'Juru'), ('ID', 'Juru Tingkat 1'), ('IIA', 'Pengatur Muda'), ('IIB', 'Pengatur Muda Tingkat 1'), ('IIC', 'Pengatur'), ('IID', 'Pengatur Tingkat 1'), ('IIIA', 'Penata Muda'), ('IIIB', 'Penata Muda Tingkat 1'), ('IIIC', 'Penata'), ('IIID', 'Penata Tingkat 1'), ('IVA', 'Pembina'), ('IVB', 'Pembina Tingkat 1'), ('IVC', 'Pembina Utama Muda'), ('IVD', 'Pembina Utama Madya'), ('IVE', 'Pembina Utama')], default='IA', max_length=4)),
                ('golongan_ruang_pangkat', models.CharField(max_length=200)),
                ('nomor_sk_pangkat', models.CharField(max_length=200)),
                ('tanggal_sk_pangkat', models.DateField()),
                ('tmt_pangkat', models.CharField(max_length=200)),
                ('file_sk_pangkat', models.FileField(upload_to='media/pangkat/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id_jabatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jabatan', models.CharField(choices=[('1', 'Inspektur'), ('2', 'Sekretaris Inspektorat'), ('3', 'Kepala Sub Bagian Administrasi dan Umum'), ('4', 'Inspektur Pembantu I'), ('5', 'Inspektur Pembantu II'), ('6', 'Inspektur Pembantu III'), ('7', 'Inspektur Pembantu IV'), ('8', 'Inspektur Pembantu Khusus'), ('9', 'JF Auditor Pelaksana'), ('10', 'JF Auditor Pelaksana Lanjutan'), ('11', 'JF Auditor Penyelia'), ('12', 'JF Auditor Pertama'), ('13', 'JF Auditor Madya'), ('14', 'JF Auditor Utama'), ('15', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Pertama'), ('16', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Muda'), ('17', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Madya'), ('18', 'JF Auditor Kepegawaian Pertama'), ('19', 'JF Auditor Kepegawaian Muda'), ('20', 'JF Auditor Kepegawaian Madya'), ('21', 'JF Analis Keuangan Pusat dan Daerah Ahli Pertama'), ('22', 'JF Analis Keuangan Pusat dan Daerah Ahli Muda'), ('23', 'JF Analis Keuangan Pusat dan Daerah Ahli Madya'), ('24', 'JF Perencana Ahli Pertama'), ('25', 'JF Perencana Ahli Muda'), ('26', 'JF Perencana Ahli Madya'), ('27', 'JF Penata Laksana Barang Terampil'), ('28', 'JF Penata Laksana Barang Mahir'), ('29', 'JF Penata Laksana Barang Penyelia'), ('30', 'Analis Tindak Lanjut Laporan Hasil Pemeriksaan'), ('31', 'Analis Pengawasan Intern Pemerintah'), ('32', 'Analis Hasil Pengawasan dan Pengaduan Masyarakat'), ('33', 'Pengelola Data Laporan dan Pengaduan'), ('34', 'Penelaah Laporan Hasil Pemeriksaan dan Kerugian Negara'), ('35', 'Penyusun Rencana Kebutuhan Sarana dan Prasarana'), ('36', 'Pengelola Sarana dan Prasarana Kantor'), ('37', 'Pengelola Sistem Informasi Manajemen Kepegawaian'), ('38', 'Pengadministrasi Umum'), ('39', 'Pengemudi'), ('40', 'Petugas Keamanan'), ('41', 'Pramu Kebersihan'), ('42', 'Bendahara'), ('43', 'Penata Laporan Keuangan'), ('44', 'Pengelola Keuangan'), ('45', 'Pengevaluasi Program dan Kinerja'), ('46', 'Penyusun Rencana Kegiatan dan Anggaran'), ('47', 'Pengelola Monitoring dan Evaluasi'), ('48', 'Pengadministrasi Perencanaan dan Program')], max_length=2)),
                ('nomor_sk_jabatan', models.CharField(max_length=200)),
                ('tanggal_sk_jabatan', models.DateField()),
                ('tmt_jabatan', models.CharField(max_length=200)),
                ('file_sk_jabatan', models.FileField(upload_to='media/jabatan/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diklat',
            fields=[
                ('id_diklat', models.AutoField(primary_key=True, serialize=False)),
                ('nama_diklat', models.CharField(max_length=200)),
                ('tanggal_mulai_diklat', models.DateField(blank=True)),
                ('tanggal_selesai_diklat', models.DateField(blank=True)),
                ('nomor_sertifikat_diklat', models.CharField(max_length=200)),
                ('tanggal_sertifikat_diklat', models.DateField()),
                ('file_sertifikat_diklat', models.FileField(upload_to='media/diklat/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AngkaKredit',
            fields=[
                ('id_pak', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_pak', models.CharField(max_length=200)),
                ('tanggal_pak', models.DateField()),
                ('nilai_pak', models.IntegerField()),
                ('masa_penilaian_pak', models.CharField(choices=[('Semester Ganjil', 'Semester Ganjil'), ('Semester Genap', 'Semester Genap')], max_length=200)),
                ('file_pak', models.FileField(upload_to='media/angkaKredit/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
