# Generated by Django 4.2.3 on 2023-08-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='nama_jabatan',
            field=models.CharField(choices=[('1', 'Inspektur'), ('2', 'Sekretaris Inspektorat'), ('3', 'Kepala Sub Bagian Administrasi dan Umum'), ('4', 'Inspektur Pembantu I'), ('5', 'Inspektur Pembantu II'), ('6', 'Inspektur Pembantu III'), ('7', 'Inspektur Pembantu IV'), ('8', 'Inspektur Pembantu Khusus'), ('9', 'JF Auditor Pelaksana'), ('10', 'JF Auditor Pelaksana Lanjutan'), ('11', 'JF Auditor Penyelia'), ('12', 'JF Auditor Pertama'), ('13', 'JF Auditor Madya'), ('14', 'JF Auditor Muda'), ('15', 'JF Auditor Utama'), ('16', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Pertama'), ('17', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Muda'), ('18', 'JF Pengawas Penyelenggaraan Urusan Pemerintahan Daerah Madya'), ('19', 'JF Auditor Kepegawaian Pertama'), ('20', 'JF Auditor Kepegawaian Muda'), ('21', 'JF Auditor Kepegawaian Madya'), ('22', 'JF Analis Keuangan Pusat dan Daerah Ahli Pertama'), ('23', 'JF Analis Keuangan Pusat dan Daerah Ahli Muda'), ('24', 'JF Analis Keuangan Pusat dan Daerah Ahli Madya'), ('25', 'JF Perencana Ahli Pertama'), ('26', 'JF Perencana Ahli Muda'), ('27', 'JF Perencana Ahli Madya'), ('28', 'JF Penata Laksana Barang Terampil'), ('29', 'JF Penata Laksana Barang Mahir'), ('30', 'JF Penata Laksana Barang Penyelia'), ('31', 'Analis Tindak Lanjut Laporan Hasil Pemeriksaan'), ('32', 'Analis Pengawasan Intern Pemerintah'), ('33', 'Analis Hasil Pengawasan dan Pengaduan Masyarakat'), ('34', 'Pengelola Data Laporan dan Pengaduan'), ('35', 'Penelaah Laporan Hasil Pemeriksaan dan Kerugian Negara'), ('36', 'Penyusun Rencana Kebutuhan Sarana dan Prasarana'), ('37', 'Pengelola Sarana dan Prasarana Kantor'), ('38', 'Pengelola Sistem Informasi Manajemen Kepegawaian'), ('39', 'Pengadministrasi Umum'), ('40', 'Pengemudi'), ('41', 'Petugas Keamanan'), ('42', 'Pramu Kebersihan'), ('43', 'Bendahara'), ('44', 'Penata Laporan Keuangan'), ('45', 'Pengelola Keuangan'), ('46', 'Pengevaluasi Program dan Kinerja'), ('47', 'Penyusun Rencana Kegiatan dan Anggaran'), ('48', 'Pengelola Monitoring dan Evaluasi'), ('49', 'Pengadministrasi Perencanaan dan Program')], max_length=2),
        ),
    ]
