# Generated by Django 4.2.3 on 2023-08-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_jabatan_nama_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkakredit',
            name='masa_penilaian_pak',
            field=models.DateField(),
        ),
    ]
