# Generated by Django 4.2.3 on 2023-08-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_alter_angkakredit_masa_penilaian_pak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkakredit',
            name='nilai_pak',
            field=models.FloatField(),
        ),
    ]
